# Generated by Django 5.2.7 on 2025-10-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COMPANY', 'Company')], default='INDIVIDUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='subscription_plan',
            field=models.CharField(choices=[('FREE', 'Free'), ('STANDARD', 'Standard'), ('ENTERPRISE', 'Enterprise')], default='FREE', max_length=20),
        ),
    ]
