services:
  app:
    - type: web
      name: sensorfusionbackend
      env: web
      runtime: python
      # buildCommand: "./build.sh"
      startCommand: "daphne config.asgi:application"
      envVars:
        - key: DATABASE_URL
          fromDatabase:
             name: remote_sensor_db
             property: connectionString
        - key: SECRET_KEY
          generateValue: False
        - key: WEB_CONCURRENCY
          value: 4


 