databases:
  - name: remote_sensor_db
    databaseName: remote_sensor_db
    user: remote_sensor_db

services:
  app:
    - type: web
      name: sensorfusionbackend
      env: web
      runtime: python
      buildCommand: ""
      startCommand: "daphne config.asgi:application"
      envVars:
        - key: DATABASE_URL
          fromDatabase:
             name: remote_sensor_db
             property: connectionString
        - key: SECRET_KEY
          generateValue: False
        - key: WEB_CONCURRENCY
          value: 4
        - ports:
           - 8000 
 