# Generated by Django 4.2.7 on 2023-11-11 15:24

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_sensor"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data", models.TextField()),
                ("metadata", models.TextField(blank=True)),
                ("data_type", models.CharField(blank=True, max_length=100)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("unit_of_measurement", models.CharField(blank=True, max_length=50)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.sensor",
                        verbose_name="Sensor",
                    ),
                ),
            ],
        ),
    ]
