# Generated by Django 4.2.7 on 2023-11-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sensordata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('viewer', 'Viewer'), ('operator', 'Operator')], max_length=100),
        ),
    ]
