# Generated by Django 5.2.7 on 2025-11-01 22:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('fields', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Sensor Name')),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('data_format', models.CharField(blank=True, help_text='Expected data format, e.g. JSON, CSV', max_length=100)),
                ('communication_mode', models.CharField(blank=True, help_text='e.g. MQTT, HTTP, LoRa, NB-IoT', max_length=150)),
                ('mqtt_key', models.CharField(editable=False, help_text='MQTT Key credential for this sensor', max_length=128, unique=True)),
                ('storage_limit_gb', models.PositiveIntegerField(default=1)),
                ('data_retention_days', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('installation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to=settings.AUTH_USER_MODEL, verbose_name='Sensor Owner')),
                ('sensor_type', models.ForeignKey(help_text='Type of sensor e.g. temperature, humidity', on_delete=django.db.models.deletion.CASCADE, to='sensors.sensortype')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensors',
                'ordering': ['-updated_at'],
            },
        ),
    ]
