# Generated by Django 5.2.7 on 2025-11-02 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='mqtt_key',
        ),
        migrations.CreateModel(
            name='SensorCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mqtt_key', models.CharField(editable=False, help_text='MQTT Key credential for this sensor', max_length=255, unique=True)),
                ('mqtt_username', models.CharField(blank=True, max_length=255)),
                ('topics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sensors.sensor')),
            ],
            options={
                'unique_together': {('id', 'mqtt_key')},
            },
        ),
    ]
