# Generated by Django 5.2.7 on 2025-11-02 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_remove_sensor_mqtt_key_sensorcredentials'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sensorcredentials',
            unique_together=set(),
        ),
    ]
