# Generated by Django 5.2.7 on 2025-11-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_alter_sensorcredentials_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensortype',
            name='fields_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
